## Credit Card Fraud Detection
### 02 - Data Preprocessing

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_csv("../data/raw/creditcard.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
print("Original shape:", df.shape)

print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

Original shape: (284807, 31)
Duplicate rows: 1081
Shape after removing duplicates: (283726, 31)

In [5]:
X = df.drop("Class", axis=1)
y = df["Class"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (283726, 30)
Target shape: (283726,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (226980, 30)
Testing data: (56746, 30)

In [7]:
print("Training class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

Training class distribution:
Class
0    226602
1       378
Name: count, dtype: int64

Testing class distribution:
Class
0    56651
1       95
Name: count, dtype: int64

In [8]:
print("Training fraud percentage:",
      round(y_train.mean() * 100, 4), "%")

print("Testing fraud percentage:",
      round(y_test.mean() * 100, 4), "%")

Training fraud percentage: 0.1665 %
Testing fraud percentage: 0.1674 %

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[["Time", "Amount"]] = scaler.fit_transform(
    X_train[["Time", "Amount"]]
)

X_test_scaled[["Time", "Amount"]] = scaler.transform(
    X_test[["Time", "Amount"]]
)

print("Training data shape:", X_train_scaled.shape)
print("Testing data shape:", X_test_scaled.shape)

print("\nScaled training features:")
X_train_scaled[["Time", "Amount"]].describe()

Training data shape: (226980, 30)
Testing data shape: (56746, 30)

Scaled training features:

               Time        Amount
count  2.269800e+05  2.269800e+05
mean  -1.522636e-16  7.487965e-17
std    1.000002e+00  1.000002e+00
min   -1.998400e+00 -3.596386e-01
25%   -8.561822e-01 -3.364866e-01
50%   -2.123526e-01 -2.697972e-01
75%    9.363191e-01 -4.287453e-02
max    1.640237e+00  7.962087e+01

In [10]:
from pathlib import Path

# Create processed data folder
processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

# Save features and target separately
X_train_scaled.to_csv(processed_dir / "X_train.csv", index=False)
X_test_scaled.to_csv(processed_dir / "X_test.csv", index=False)

y_train.to_csv(processed_dir / "y_train.csv", index=False)
y_test.to_csv(processed_dir / "y_test.csv", index=False)

print("All processed datasets saved successfully!")
print("Files:", [file.name for file in processed_dir.iterdir()])

All processed datasets saved successfully!
Files: ['feature_importance.csv', 'X_test.csv', 'X_train.csv', 'y_test.csv', 'y_train.csv']

In [11]:
print("Training features:", X_train_scaled.shape)
print("Testing features:", X_test_scaled.shape)

print("\nTraining fraud cases:", int(y_train.sum()))
print("Testing fraud cases:", int(y_test.sum()))

Training features: (226980, 30)
Testing features: (56746, 30)

Training fraud cases: 378
Testing fraud cases: 95

In [12]:
from sklearn.preprocessing import StandardScaler
import joblib
import os

# Load the original training data
X_train_original = pd.read_csv("../data/processed/X_train.csv")

# Create scaler
scaler = StandardScaler()

# Fit scaler on Time and Amount only
scaler.fit(X_train_original[["Time", "Amount"]])

print("Scaler recreated successfully!")

Scaler recreated successfully!

In [13]:
os.makedirs("../models", exist_ok=True)

joblib.dump(scaler, "../models/scaler.pkl")

print("Scaler saved successfully!")

Scaler saved successfully!

In [14]:
print(os.listdir("../models"))

['fraud_detection_model.pkl', 'scaler.pkl']